# Generated by Django 4.2.2 on 2023-06-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=2)),
                ('summer', models.CharField(blank=True, max_length=2)),
                ('autumn', models.CharField(blank=True, max_length=2)),
                ('spring', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_title', models.CharField(blank=True, max_length=255)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PEN', 'pending'), ('ACC', 'accepted'), ('REJ', 'rejected')], default='NEW', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MountainImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountains.mountain')),
            ],
        ),
        migrations.AddField(
            model_name='mountain',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.users'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='coords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.coords'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.level'),
        ),
    ]
